version: "2"
services:

  index:
    image: nginx:alpine
    restart: always
    container_name: nginx_index
    ports:
      - 80:80
    volumes:
      - ./index/public:/usr/share/nginx/html:ro

  samba:
    image: dperson/samba:rpi
    container_name: samba
    restart: always
    command: '-u "pi;9876;" -s "disco;/disco;yes;no;no"'
    stdin_open: true
    tty: true
    ports:
      - 139:139
      - 445:445
    volumes:
      - /usr/share/zoneinfo/Europe/Madrid:/etc/localtime
      - ${DISK}:/disco

  minidlna:
    image: cytomich/rpi-docker-minidlna
    volumes:
      - ${DISK}/:/media
    environment:
      - MINIDLNA_MEDIA_DIR=/media
      - MINIDLNA_PORT=8200
      - MINIDLNA_FRIENDLY_NAME=fotos-video
    network_mode: "host"
    restart: always

  rpimonitor:
    image: michaelmiklis/rpi-monitor:latest
    restart: always
    container_name: rpi-monitor
    ports:
      - 8888:8888
    volumes:
      - /boot:/boot
      - /sys:/dockerhost/sys:ro
      - /etc:/dockerhost/etc:ro
      - /proc:/dockerhost/proc:ro
      - /usr/lib:/dockerhost/usr/lib:ro
    devices:
      - /dev/vchiq:/dev/vchiq
      - /dev/vcsm:/dev/vcsm

  rsnapshot:
    image: pablokbs/rsnapshot-cron
    restart: always
    volumes:
      - ${DISK}/Documentos:/host/Documentos:ro
      - ${DISK}/snapshots:/snapshots
      - /usr/share/zoneinfo/Europe/Madrid:/etc/localtime
    environment:
      - BACKUP_DIRECTORIES=/host/      snapshots/
      - CRON_DAILY=0 0 5 * * *
      - CRON_WEEKLY=0 0 6 * * 1
      - CRON_MONTHLY=0 30 6 1 * *
      - RSNAPSHOT_HOURLY_TIMES=0
      - RSNAPSHOT_DAILY_TIMES=7
      - RSNAPSHOT_WEEKLY_TIMES=4
      - RSNAPSHOT_MONTHLY_TIMES=3
 
  filebrowser:
    image : filebrowser/filebrowser:pi
    container_name: filebrowser
    restart: always
    volumes:
      - ./filebrowser/filebrowser.db:/database.db
      - ./filebrowser/filebrowser.json:/.filebrowser.json
      - ${DISK}/:/srv
    ports:
      - 8088:80
